theme: jekyll-theme-leap-day
show_downloads: true
github:
  current_version: v0.3
  linux_url: FFXIV_TexTools_CLI-Linux-Bundled
  mac_url: FFXIV_TexTools_CLI-Mac-Bundled
  uni_url: FFXIV_TexTools_CLI-Universal.zip
